import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import {
  ClerkProvider,

} from '@clerk/nextjs'
import Providers from "@/components/Providers";

import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { CircleUser, MenuIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import DashBoardNavigation from "./(admin)/admin/components/dashBoardNavigation";
import NavBar from "@/components/navBar";
import { currentUser } from "@clerk/nextjs/server";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  console.log(user);

  const email = user ? user.emailAddresses[0].emailAddress : '';
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-full flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8`}
          >
            <header className="sticky top-0 flex h-16 items-center justify-between gap-4 border-b bg-white">
              <nav className="hidden font-medium md:flex md:items-center md:gap-5 md:text-sm lg:gap-6">
                <NavBar email={email} />
              </nav>
              <Sheet>
                <SheetTrigger asChild>
                  <Button className="shrink-0 md:hidden" variant="outline" size="icon">
                    <MenuIcon className="w-5 h-5" />
                  </Button>
                </SheetTrigger>
                <SheetContent side="left">
                  <nav className="flex flex-col gap-6 text-lg font-medium mt-5">
                    <NavBar email={email} />
                  </nav>
                </SheetContent>
              </Sheet>

              <Image
                src={user?.imageUrl || "/default-image.png"}
                alt="Logo"
                width={100}
                height={100}
                className="rounded-full w-10 h-10 cursor-pointer"

              />
            </header>
            {children}
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  );
}
