import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import {
  ClerkProvider,

} from '@clerk/nextjs'
import Providers from "@/components/Providers";

import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { CircleUser, MenuIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import DashBoardNavigation from "./(admin)/admin/components/dashBoardNavigation";
import NavBar from "@/components/navBar";
import { currentUser } from "@clerk/nextjs/server";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  console.log(user);

  const email = user ? user.emailAddresses[0].emailAddress : '';
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-full flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8`}
          >

            {children}
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  );
}
